version: 0.0  # CodeDeploy 버전
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes
# CodeDeploy에서 EC2서버로 넘겨준 파일들은 모두 ec2-user권한을 갖도록 설정
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  AfterInstall:  # 배포를 완료한 후 실행되는 스크립트
    - location: restartup.sh
      timeout: 60
      runas: ec2-user