version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Pre-build phase
  build:
    commands:
      - echo Build started on `date`
      - echo "Starting build process"
      - mkdir -p target
      - echo "Packaging application"
      - cd webapps
      - zip -r ../target/projectcode.war ROOT/
      - echo "Build process complete"
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.war
    - appspec.yml
    - restartup.sh
  discard-paths: no